# Basic Ingress for GKE(NodePort) if we don't want use LoadBalancer

#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  annotations:
#    kubernetes.io/ingress.class: nginx
#  name: basic-ingress
#spec:
#  backend:
#    serviceName: debugkit
#    servicePort: 80
#---
### Ingress dla wielu serwisów pod jednym IP dla kilku domen
###https://kubernetes.io/docs/concepts/services-networking/ingress/#name-based-virtual-hosting
#Instalcja Ingress-Controlera:
#helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#helm repo add stable https://kubernetes-charts.storage.googleapis.com/
#helm repo update
#helm install ingress-nginx ingress-nginx/ingress-nginx
#Doc: https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-airflow
#   namespace: ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx-tenants
# spec:
#   rules:
#   - host: airflow.tk
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: debugkit-svc
#           servicePort: 8080
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-keycloak
#   namespace: keycloak
#   annotations:
#     kubernetes.io/ingress.class: nginx-keycloak
# spec:
#   rules:
#   - host: keycloak.airflow.tk
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: debugkit-svc
#           servicePort: 8080


### INGRESS POLICY ###
#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-all-ingress
#spec:
#  podSelector: {}
#  ingress:
#  - {}
#  policyTypes:
#  - Ingress

#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-all-egress
#spec:
#  podSelector: {}
#  egress:
#  - {}
#  policyTypes:
#  - Egress
#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: default-allow-all
#spec:
#  podSelector: {}
#  policyTypes:
#  - Ingress
#  - Egress
