# Dodać healthcheck

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: debugkit
  name: debugkit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debugkit
  serviceName: debugkit
  template:
    metadata:
      labels:
        app: debugkit
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - debugkit
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: debek/k8s-debugkit:v1
        imagePullPolicy: Always
        name: k8s-debugkit
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: debugkit
  name: debugkit
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: debugkit
  type: NodePort
