# Dodać healthcheck

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: debugkit
  name: debugkit
spec:
  selector:
    matchLabels:
      app: debugkit
  template:
    metadata:
      labels:
        app: debugkit
    spec:
      containers:
      - image: debek/k8s-debugkit:v1
        imagePullPolicy: Always
        name: k8s-debugkit
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: debugkit
  name: debugkit
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: debugkit
  type: NodePort
